// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Dialog: typeof import('./components/UI/Dialog.vue')['default']
    Footer: typeof import('./components/Footer/Footer.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    HeroText: typeof import('./components/HeroText.vue')['default']
    IcBaselineClose: typeof import('~icons/ic/baseline-close')['default']
    IcBaselineContentCopy: typeof import('~icons/ic/baseline-content-copy')['default']
    IcBaselineDarkMode: typeof import('~icons/ic/baseline-dark-mode')['default']
    IcBaselineDelete: typeof import('~icons/ic/baseline-delete')['default']
    IcBaselineImage: typeof import('~icons/ic/baseline-image')['default']
    IcBaselineLightMode: typeof import('~icons/ic/baseline-light-mode')['default']
    IcBaselineLogin: typeof import('~icons/ic/baseline-login')['default']
    IcBaselineLogout: typeof import('~icons/ic/baseline-logout')['default']
    IcBaselineOpenInNew: typeof import('~icons/ic/baseline-open-in-new')['default']
    IcBaselineTableRows: typeof import('~icons/ic/baseline-table-rows')['default']
    IconButton: typeof import('~icons/ic/on-button')['default']
    ImageTable: typeof import('./components/Table/ImageTable.vue')['default']
    Input: typeof import('./components/UI/Input.vue')['default']
    Login: typeof import('./components/Form/Login.vue')['default']
    LoginButton: typeof import('./components/Login/LoginButton.vue')['default']
    LoginTabs: typeof import('./components/Login/LoginTabs.vue')['default']
    MdiArrowRight: typeof import('~icons/mdi/arrow-right')['default']
    MdiClose: typeof import('~icons/mdi/close')['default']
    MdiEyeOffOutline: typeof import('~icons/mdi/eye-off-outline')['default']
    MdiEyeOutline: typeof import('~icons/mdi/eye-outline')['default']
    MdiGithub: typeof import('~icons/mdi/github')['default']
    MdiGitlab: typeof import('~icons/mdi/gitlab')['default']
    MdiImage: typeof import('~icons/mdi/image')['default']
    MdiKnife: typeof import('~icons/mdi/knife')['default']
    MdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    MdiLoading: typeof import('~icons/mdi/loading')['default']
    MdiTwitter: typeof import('~icons/mdi/twitter')['default']
    MdiViewList: typeof import('~icons/mdi/view-list')['default']
    Modal: typeof import('./components/UI/Modal.vue')['default']
    Navbar: typeof import('./components/Navbar/Navbar.vue')['default']
    README: typeof import('./components/README.md')['default']
    ReloadPrompt: typeof import('./components/UI/ReloadPrompt.vue')['default']
    ShortUrl: typeof import('./components/Form/ShortUrl.vue')['default']
    Signup: typeof import('./components/Form/Signup.vue')['default']
    StoredUrls: typeof import('./components/Table/StoredUrls.vue')['default']
    Toggle: typeof import('./components/Table/Toggle.vue')['default']
    UserInfo: typeof import('./components/Navbar/UserInfo.vue')['default']
  }
}

export { }
