// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default'];
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default'];
    CarbonLanguage: typeof import('~icons/carbon/language')['default'];
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default'];
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default'];
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default'];
    Footer: typeof import('./components/Footer/Footer.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    ImageTable: typeof import('./components/Table/ImageTable.vue')['default']
    MdiDelete: typeof import('~icons/mdi/delete')['default']
    MdiGit: typeof import('~icons/mdi/git')['default'];
    MdiGithub: typeof import('~icons/mdi/github')['default']
    MdiGitlab: typeof import('~icons/mdi/gitlab')['default']
    MdiImage: typeof import('~icons/mdi/image')['default']
    MdiKnife: typeof import('~icons/mdi/knife')['default']
    MdiLink: typeof import('~icons/mdi/link')['default']
    MdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    MdiLinkVariant: typeof import('~icons/mdi/link-variant')['default']
    MdiLoading: typeof import('~icons/mdi/loading')['default']
    MdiLoginVariant: typeof import('~icons/mdi/login-variant')['default']
    MdiLogoutVariant: typeof import('~icons/mdi/logout-variant')['default']
    MdiTableEye: typeof import('~icons/mdi/table-eye')['default']
    MdiTableEyeOff: typeof import('~icons/mdi/table-eye-off')['default']
    MdiTwitter: typeof import('~icons/mdi/twitter')['default']
    MdiVariant: typeof import('~icons/mdi/variant')['default']
    MdiViewList: typeof import('~icons/mdi/view-list')['default']
    MdiWeatherNight: typeof import('~icons/mdi/weather-night')['default']
    MdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    Navbar: typeof import('./components/Navbar/Navbar.vue')['default']
    README: typeof import('./components/README.md')['default']
    ShortUrl: typeof import('./components/Form/ShortUrl.vue')['default']
    SocialLink: typeof import('./components/Footer/SocialLink.vue')['default'];
    StoredUrls: typeof import('./components/Table/StoredUrls.vue')['default']
    TextLink: typeof import('./components/Footer/TextLink.vue')['default'];
  }
}

export { }
